### ISSUE TITLE
Got some error about 'Property accProvisionInput of details is out of range' when provision with ACI 6.0(4)

### ISSUE THREAD

**Issue by tumarha** [noironetworks/acc-provision#1131]
I try to integrate ACI 6.0(4) and Openshift 4.14, after I try to run ACC-PROV tool, I got some error 

[root@ocpacc ~]# acc-provision -a -c acc-prov_2.yaml -u admin -p 123Cisco123! -f openshift-4.14-esx -o aci-containers.yaml -z manifests.tar.gz                
/usr/local/lib/python3.6/site-packages/OpenSSL/_util.py:6: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography. The next release of cryptography will remove support for Python 3.6.
  from cryptography.hazmat.bindings.openssl.binding import Binding
INFO: Loading configuration from "acc-prov_2.yaml"
INFO: Using configuration flavor openshift-4.14-esx
INFO: Generating certs for kubernetes controller
INFO:   Private key file: "user-ocp414.key"
INFO:   Certificate file: "user-ocp414.crt"
INFO: Writing kubernetes infrastructure YAML to aci-containers.yaml
INFO: Writing ACI CNI operator tar to manifests.tar.gz
INFO: Apply infrastructure YAML using:
INFO:   oc apply -f aci-containers.yaml
INFO: Delete stale objects from older deployments using:
INFO:   oc -n aci-containers-system delete configmap,secret,serviceaccount,daemonset,deployment,clusterrolebinding,clusterrole -l  'aci-containers-config-version,aci-containers-config-version notin (19b7d26b-1fa1-4ac1-8dfe-687496c941f9)'
INFO: Provisioning configuration in APIC
ERR:  Error in provisioning /api/node/mo/comp/prov-OpenShift/ctrlr-[ocp414]-ocp414/injcont/info.json: APIC REST Error: {'attributes': {'code': '801', 'text': 'Property accProvisionInput of details is out of range'}}

however, I checked on APIC, it has already been provisioned, Tenant,BD,EPG and related configurations. So, I'm not sure this error is something I need to aware or not. I also attach yaml file on attach, please feel free to advice.

[acc-prov_2.yaml.zip](https://github.com/user-attachments/files/15642866/acc-prov_2.yaml.zip)

**Comment by g9ais** [comment]
got same issue on ACI 6.0(5) - acc_provision tries to push the entire contents of input yaml file. If it was generated with acc_provision --sample  the amount of comments just makes the string to long to push in a single POST.

can see in debug that accProvisionInput is huge

**Comment by tomflynn** [comment]
https://github.com/noironetworks/acc-provision/pull/1146 attempts to at least partially address this. Please reopen if you're still seeing issues
