### ISSUE TITLE
Baremetal flavors assume that nodes/servers are directly connected to leaf switches

### ISSUE THREAD

**Issue by hamleadm** [noironetworks/acc-provision#1152]
We use Cisco UCS bare metal servers. The UCS has an internal Fabric interconnect switch that is connected via a VPC to the leaf switch.

This require that vlans are configured as tagged in the aep, currently we do a work around by changing in the flavor.yaml. But it would be great if it can be controlled by a config parameter.  It works fine for the ESX flavors that use nested inside vm-ware then the vlans are provisioned as tagged.

**Comment by fwardzic** [comment]
You can use config option in your input file to alter the kubeapi vlan untagged default for baremetal flavor:
`net_config:
  kubeapi_vlan_mode: "regular"
`

**Comment by hamleadm** [comment]
Thanks I have missed that option.

**Comment by hamleadm** [comment]
The option worked fine.
net_config:
  kubeapi_vlan_mode: "regular"
