### ISSUE TITLE
Compatibility matrix update

### ISSUE THREAD

**Issue by ebati** [noironetworks/acc-provision#4]
Is there any timeline determined to update [compatibility matrix information in official ACI documentation](https://www.cisco.com/c/dam/en/us/td/docs/Website/datacenter/aci/virtualization/matrix/virtmatrix.html). I am asking because 1.13 is listed in `flavors.yaml` but not in matrix.

**Comment by snaiksat** [comment]
@ebati 1.13 was supported as experimental in last released version. It will be fully supported in the upcoming release, and at which point the Compatibility Matrix will also be updated.

**Comment by ebati** [comment]
Sorry for writing to closed issue again, but i saw the new release and just wanted to ask if this release(4.1) will officially support kuberenetes 1.13?

**Comment by snaiksat** [comment]
Yes, we do have the new release coming up and 1.13 will be supported in that.

**Comment by ebati** [comment]
I am writing yet again sorry for inconvenience. In the [compatibility matrix](https://www.cisco.com/c/dam/en/us/td/docs/Website/datacenter/aci/virtualization/matrix/virtmatrix.html) the new column for 4.1 is added but row for Kubernetes Upstream 1.13 does not exists.

**Comment by snaiksat** [comment]
@ebati no worries and thanks for tracking. ACI 4.1 is released, but the ACI CNI plugin solution has not yet been released. Once its released, you will also see the update in the matrix.

**Comment by snaiksat** [comment]
@ebati the matrix has been updated.

**Comment by ebati** [comment]
Thank you very much :+1:
