### ISSUE TITLE
Update acc-provision tool to support latest openshift releases

### ISSUE THREAD

**Issue by enrico2828** [noironetworks/acc-provision#602]
When I run the acc-provision tool version 5.2.3.1 the available flavors for openshift are outdated. The latest baremetal is 4.6. Can it be updated for Openshift 4.9 (and 4.10 has been released recently). 
Thanks a lot!

```
INFO: Available configuration flavors:
INFO: openshift-4.7-openstack:	Red Hat OpenShift Container Platform 4.7 on OpenStack
INFO: openshift-4.6-openstack:	Red Hat OpenShift Container Platform 4.6 on OpenStack
INFO: openshift-4.6-baremetal:	Red Hat OpenShift Container Platform 4.6 on Baremetal
INFO: openshift-4.5-openstack:	Red Hat OpenShift Container Platform 4.5 on OpenStack
INFO: openshift-4.8-esx:	Red Hat OpenShift Container Platform 4.8 on ESX
INFO: openshift-4.7-esx:	Red Hat OpenShift Container Platform 4.7 on ESX
INFO: openshift-4.6-esx:	Red Hat OpenShift Container Platform 4.6 on ESX
INFO: openshift-4.5-esx:	Red Hat OpenShift Container Platform 4.5 on ESX
INFO: openshift-3.11:	Red Hat OpenShift Container Platform 3.11
```

**Comment by PariyaAshok** [comment]
acc-provision tool is updated to support latest OCP releases(till 4.10).

noiro@k8s-bm-1-extrtr:~$ acc-provision --version
5.2.3.3rc1

noiro@k8s-bm-1-extrtr:~$ acc-provision --list-flavors
INFO: Available configuration flavors:
INFO: openshift-4.10-baremetal:	Red Hat OpenShift Container Platform 4.10 on Baremetal
INFO: openshift-4.9-baremetal:	Red Hat OpenShift Container Platform 4.9 on Baremetal
INFO: openshift-4.8-baremetal:	Red Hat OpenShift Container Platform 4.8 on Baremetal
INFO: openshift-4.7-baremetal:	Red Hat OpenShift Container Platform 4.7 on Baremetal
INFO: openshift-4.6-baremetal:	Red Hat OpenShift Container Platform 4.6 on Baremetal
INFO: openshift-4.10-openstack:	Red Hat OpenShift Container Platform 4.10 on OpenStack
INFO: openshift-4.9-openstack:	Red Hat OpenShift Container Platform 4.9 on OpenStack
INFO: openshift-4.8-openstack:	Red Hat OpenShift Container Platform 4.8 on OpenStack
INFO: openshift-4.7-openstack:	Red Hat OpenShift Container Platform 4.7 on OpenStack
INFO: openshift-4.6-openstack:	Red Hat OpenShift Container Platform 4.6 on OpenStack
INFO: openshift-4.10-esx:	Red Hat OpenShift Container Platform 4.10 on ESX
INFO: openshift-4.9-esx:	Red Hat OpenShift Container Platform 4.9 on ESX
INFO: openshift-4.8-esx:	Red Hat OpenShift Container Platform 4.8 on ESX
INFO: openshift-4.7-esx:	Red Hat OpenShift Container Platform 4.7 on ESX
INFO: openshift-4.6-esx:	Red Hat OpenShift Container Platform 4.6 on ESX
INFO: kubernetes-1.23:	Kubernetes 1.23
INFO: kubernetes-1.22:	Kubernetes 1.22
INFO: kubernetes-1.21:	Kubernetes 1.21
INFO: kubernetes-1.20:	Kubernetes 1.20
INFO: RKE-1.2.3:	Rancher Kubernetes Engine min version 1.2.3
