### ISSUE TITLE
 Invalid configuration for aci_config/system_id

### ISSUE THREAD

**Issue by franc01s** [noironetworks/acc-provision#63]
I got Invalid configuration for aci_config/system_id: aci_config/system_id during acc-provision command because system_id contains "-" char.
It is related to config_validate/checks
```
       "aci_config/system_id": (get(("aci_config", "system_id")),
                                 lambda x: required(x) and isname(x, 32))
```
My network teams said that is not possible to rename tenant/system-id.
Is the system-id dash is really avoid on ACI side or is this a python issue?

**Comment by snaiksat** [comment]
@franc01s To answer your question, this is to avoid on the ACI side.

**Comment by franc01s** [comment]
Dash seems supported so, is there any reason to not remove - as well in the checks?

```
isname = lambda x, l: (1 < len(x) < l) and \
        x[0].isalpha() and x.replace('_', '').x.replace(‘-‘,’’).isalnum() \
        if x else Raise(Exception("Invalid name"))
```

**Comment by snaiksat** [comment]
@franc01s I believe in older ACI releases it was not supported and we need to be backward compatible.
